import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, Button, Typography } from "@mui/material";
import OptionList from "../components/OptionList";
import { useRouter } from "next/router";
import { baseUrl } from "../config/api";

const getMappedInfo = (array: any[], accesor: string) =>
  array.map((object) => object[accesor]);

export async function getStaticProps() {
  const { drinks: ingredients }: any = await (
    await fetch(`${baseUrl}/list.php?i=list`)
  ).json();
  const { drinks: categories }: any = await (
    await fetch(`${baseUrl}/list.php?c=list`)
  ).json();
  const { drinks: alcoholic }: any = await (
    await fetch(`${baseUrl}/list.php?a=list`)
  ).json();

  return {
    props: {
      ingredients: getMappedInfo(ingredients, "strIngredient1"),
      categories: getMappedInfo(categories, "strCategory"),
      alcoholic: getMappedInfo(alcoholic, "strAlcoholic"),
    },
  };
}

export default function Home({
  ingredients,
  categories,
  alcoholic,
}: {
  ingredients: string[];
  categories: string[];
  alcoholic: string[];
}) {
  const { title, paddingContent, textCenter } = styles;
  const router = useRouter();
  return (
    <>
      <Head>
        <title>The cocktail app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Typography variant="h4" className={`${title} ${textCenter}`}>
        The Cocktail app
      </Typography>

      <Box className={textCenter}>
        <Button
          variant="contained"
          color="secondary"
          onClick={() => router.push("/random-drink")}
        >
          I want a random cocktail
        </Button>
      </Box>

      <Box className={paddingContent}>
        <OptionList title="Alcoholic" values={alcoholic} />
        <OptionList title="Categories" values={categories} />
        <OptionList title="Ingredients" values={ingredients} />
      </Box>
    </>
  );
}
